baseurl: '/quality'
url: 'https://qualitystandardohio.com/'
title: 'Quality Standard Ohio'
telefono: "(614) 602-5494"
whatsapp: "+16143843087"
address: 2211 Dublin Rd Unit 467 Columbus, Ohio 43228
email: "support@qualitystandardoh.com"
maps: https://maps.app.goo.gl/LAmA8gQZFBxwKak28

markdown: kramdown

permalink: :slug

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  specialized:
    output: true
    permalink: /specialized/:path
  commercial:
    output: true
    permalink: /commercial/:path
  residential:
    output: true
    permalink: /residential/:path
  areas:
    output: true
    permalink: /areas/:path
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

paginate: 10  # Número de posts por página
paginate_path: "/blog/page/:num/"  # URL para las páginas
plugins:
  - jekyll-paginate